config/routes.rb
Rails.application.routes.draw do

  devise_for :doctors
  root to: 'pages#home'

  # Dashboard des doctors / accueil controle
  get 'doctors/dashboard', to: 'doctors#dashboard', as: :doctor_dashboard
  # historique des cas patients assignés au doc
  get 'doctors/history', to: 'doctors#history', as: :doctor_history

  # Le doc SELECT un case (verrouille l'attribution d'un docteur au patient et sort ce patient des autres médecins)
  post 'doctors/assign-patient', to: 'doctors#assign_patient', as: :doctor_assign_patient
  #As a doctor, I can see a patient case
  get 'doctors/patient/:id', to: 'doctors#show_patient', as: :doctor_show_patient
  #As a doctor, I can SUBMIT my answer to the patient
  post 'doctors/patient/:id', to: 'doctors#create_answer', as: :doctor_create_answer

  # page de confirmation/recap et paiement coté patient / EDIT
  get 'patients/:id/validation', to: 'patients#validation', as: :validation_patient

  #As a patient, I can pay; redirect to payment confirmation controller patients; ajouter : à ID
  get 'patients/:id/payment', to: 'patients#payment', as: :payment_patient

  #message de confirmation et remerciement suite au paiement
  get 'patients/:id/thank-you', to: 'patients#thank_you', as: :thank_you_patient

  # la show du patient est celle quand il va cliquer sur le lien du cas traité par le DR
  resources :patients, only: [:new, :create, :show, :edit, :update] do
    resources :payments, only: [:new, :create]
  end
  # ajout paiements et orders

  # edition du profil docteur
  get 'profile/edit'
  get 'profile/update'

  # page de formulaire de contact avec le site
  get '/contact', to: 'pages#contact'
  # page d'info generale
  get '/about', to: 'pages#about'


  mount Attachinary::Engine => "/attachinary"
  # devise_for :users, :controllers => { registrations:  "users/registrations" }
end

app/views/shared/_flash.html.erb
<% if flash[:alerte] %>
    <div class="alert alert-danger fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:alerte] %>
    </div>
    <% end %>
    <% if flash[:notice] %>
    <div class="alert alert-info fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:notice] %>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<div class="footer-container" style="background: #62E1A6; background-image: url('<%= image_url "background.png" %>');">
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fa fa-instagram"></i></a>
      <a href="#"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
    </div>
    <div class="footer-copyright">
        This footer is made with <i class="fa fa-heart"></i> at Le Wagon Marseille
    </div>
  </div>
</div>

app/views/shared/_form-complet-old.html.erb
<%= simple_form_for @patient, html: {id: "patient-form"} do |f| %>

      <fieldset>
        <%= f.input :last_name , input_html: { "cf-questions" => "Bonjour! Il me semble que l'on ne se soit jamais rencontré!<br>Quel est votre nom?"} %>
      </fieldset>

      <fieldset>
        <%= f.input :first_name, input_html: { "cf-questions" => "Enchanté {previous-answer}, quel est votre prénom?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :gender, collection: ["Une femme", "Un homme"], input_html: { "cf-questions" => "Êtes-vous une femme ou un homme?"} %>
        <%= f.button :submit %>
      </fieldset>

      <fieldset>
        <%= f.input :email , input_html: { "cf-questions" => "À la fin de ce questionnaire je vous enverrai votre diagnostique par email.<br> Quelle est votre adresse Email?"}%>
      </fieldset>


      <fieldset>
        <%= f.input :zip_code , input_html: { "cf-questions" => "Il est possible que j'ai besoin de vous diriger vers un dermatologue Hair'Diag proche de chez vous. <br>Quel est votre code postal?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :city , input_html: { "cf-questions" => "Quel est le nom de cette ville?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :country, collection: ["France", "Etranger"], input_html: { "cf-questions" => "Est-ce que {previous-answer} est situé en France ou à l'étranger?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :age, input_html: { "cf-questions" => "Ok, maintenant que ces formalitées d'usage sont passées, dites moi en plus sur vous. <br>Quel age avez vous?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :loss_start_date,as: :select, input_html: { "cf-questions" => "{previous-answer} ans! Quel bel age! <br>A quelle année remonte votre premiere chute de cheveux?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :relative, collection: ["aucun", "Père", "Mère", "Grand Père", "Grand Mère"], input_html: { "cf-questions" => " Quel membre de votre famille semble avoir le même problème?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :weekly_shampoo, collection: (0..8), input_html: { "cf-questions" => "Combien de shampooings faites-vous par semaine?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :dandruff, collection: ["oui","non"], input_html: { "cf-questions" => "{previous-answer} fois! Je savais que vous preniez soin de votre cuir chevelu à la seconde de notre rencontre :).<br> Avez vous des pellicules?"}%>
      </fieldset>

      <fieldset cf-questions="Ne voyez rien de personnel, je pose cette question à toutes les personnes que je rencontre:<br>Diriez vous que vous avez vous les cheveux gras ?" >
        <label for="greasy_hair-yes">Oui<input type="radio" name="patient[greasy_hair]" id="greasy_hair-yes" value="yes" tabindex="-1"
          <%= @patient.greasy_hair? ? 'checked="checked"' : "" %>>
        </label>

        <label for="greasy_hair-no">Non
          <input type="radio" name="patient[greasy_hair]" id="greasy_hair-no" value="no" tabindex="-1"
          <%= @patient.greasy_hair == false ? 'checked="checked"' : "" %>
          >
        </label>
      </fieldset>

      <fieldset>
        <%= f.input :refined_hair, collection: ["oui","non"], input_html: { "cf-questions" => "Avez vous l’impression que vos cheveux se sont affinés ?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :brushing_hair, collection: ["oui","non"], input_html: { "cf-questions" => "Entendu, faites-vous des tresses / défrisages / brushings ?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :shaving_hair, collection: ["oui","non"], input_html: { "cf-questions" => "Faites-vous un rasage régulier de tout ou une partie de votre cuir chevelu?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :scalp_density, collection: ["moyenne","bonne","très bonne"], input_html: { "cf-questions" => "Quelle est la densité à l'arrière de votre cuir chevelu?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :hair_thickness, collection: ["fin","moyen","épais"], input_html: { "cf-questions" => "Comment conciderez vous l'épaisseur de vos cheveux?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :hair_color, collection: ["blancs", "gris", "blonds", "Chatain clair",  "chatain foncé", "noir", "roux"], input_html: { "cf-questions" => "Quelle est la couleur naturelle de vos cheveux?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :hair_type, collection: ["raides", "ondulés", "bouclés", "crépus"],input_html: { "cf-questions" => "Quel est le type de vos cheveux?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :vitamines, collection: ["oui","non"], input_html: { "cf-questions" => "Prenez vous des vitamines ou des compléments alimentaires?"}%>
      </fieldset>

      <fieldset cf-questions="Etes-vous sous Minoxidil ?" >
        <label for="minoxidil-yes">Oui<input type="radio" name="patient[minoxidil]" id="minoxidil-yes" value="yes" tabindex="-1"
          <%= @patient.minoxidil? ? 'checked="checked"' : "" %>>
        </label>

        <label for="minoxidil-no">Nope
          <input type="radio" name="patient[minoxidil]" id="minoxidil-no" value="no" tabindex="-1"
          <%= @patient.minoxidil == false ? 'checked="checked"' : "" %>
          >
        </label>
      </fieldset>

      <fieldset>
        <%= f.input :minoxidil_doses, collection: [["2%",2],["5%",5]], input_html: { "cf-questions" => "A quel dosage?", "cf-conditional-patient[minoxidil]" =>"yes"}%>
      </fieldset>


      <fieldset>
        <%= f.input :finasteride, collection: ["oui","non"], input_html: { "cf-questions" => "Prenez vous du finastéride?"}%>
      </fieldset>

      <fieldset cf-questions="Avez-vous déjà eu des greffes capillaires ?" >
        <label for="hair_transplant-yes">Oui<input type="radio" name="patient[hair_transplant]" id="hair_transplant-yes" value="yes" tabindex="-1"
          <%= @patient.hair_transplant? ? 'checked="checked"' : "" %>>
        </label>

        <label for="hair_transplant-no">Nope
          <input type="radio" name="patient[hair_transplant]" id="hair_transplant-no" value="no" tabindex="-1"
          <%= @patient.hair_transplant == false ? 'checked="checked"' : "" %>
          >
        </label>
      </fieldset>

      <fieldset>
        <%= f.input :hair_transplant_technic, collection: ["F.U.E. (Unités folliculaires par extraction)","F.U.T. (Unités folliculaires par transplantation)","F.U.L. (Unités folliculaires à cheveux longs)","Aucune des trois","Ne sais pas"], input_html: { "cf-questions" => "C'est intéressant, quelle technique de transplantation a été employée ?", "cf-conditional-patient[hair_transplant]" =>"yes"}%>
      </fieldset>

      <fieldset cf-questions="A quel stade pensez vous être ?" >
        <input cf-label="stade1" type="radio" cf-image="http://res.cloudinary.com/dgbt9zicg/image/upload/Stade1_yzlrg4" name="patient[stage]" tabindex="1" value="0" cf-conditional-patient[gender]="Un homme" >
        <input cf-label="stade2" type="radio" cf-image="http://res.cloudinary.com/dgbt9zicg/image/upload/v1504186425/Stade2_jiqcsr.png" name="patient[stage]" tabindex="1" value="1" cf-conditional-patient[gender]="Un homme">
        <input cf-label="stade3" type="radio" cf-image="http://res.cloudinary.com/dgbt9zicg/image/upload/v1504186425/Stade3_sgu99f.png" name="patient[stage]" tabindex="1" value="2" cf-conditional-patient[gender]="Un homme">
        <input cf-label="stade1" type="radio" cf-image="http://res.cloudinary.com/dgbt9zicg/image/upload/v1504186425/stade1_femme_ed4vqu.png" name="patient[stage]" tabindex="1" value="0" cf-conditional-patient[gender]="Une femme" >
        <input cf-label="stade2" type="radio" cf-image="http://res.cloudinary.com/dgbt9zicg/image/upload/v1504186425/stade2_femme_gdxaoo.png" name="patient[stage]" tabindex="1" value="1" cf-conditional-patient[gender]="Une femme">
        <input cf-label="stade3" type="radio" cf-image="http://res.cloudinary.com/dgbt9zicg/image/upload/v1504186425/stade3_femme_qqafpl.png" name="patient[stage]" tabindex="1" value="2" cf-conditional-patient[gender]="Une femme">
      </fieldset>

      <fieldset>
        <%= f.input :traction_test, collection: ["0-1 cheveu","2-3 cheveux","> 3 cheveux"], input_html: { "cf-questions" => "Maintenant je vais vous demander de faire un test de tractions:<br>Assurez vous d'avoir un cuir chevelu non lavé pendant 2 jours.<br>Prenez une mèche comprenant environ 10 cheveux entre le pouce et l'index. Exercez une légère traction afin de détacher les cheveux venant facilement.<br>Combien de cheveux se sont extraits?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :restore_area, collection: ["Front","Tonsure (surface au sommet du crâne)","Totalité","Poils du corps (sourcils, barbe)"], input_html: { "cf-questions" => "Projet de restauration capillaire - quelle zone souhaitez-vous restaurer? (par ordre de priorité si plusieurs zones)"}%>
      </fieldset>

      <fieldset>
        <%= f.input :technical_preference, collection: ["F.U.E. (Unités folliculaires par extraction)","F.U.T. (Unités folliculaires par transplantation)","F.U.L. (Unités folliculaires à cheveux longs)","Aucune"], input_html: { "cf-questions" => "Quelle technique perferiez vous ?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :remark, input_html: { "cf-questions" => "Merci, j'ai toutes les informations necessaires au daignostique Hair'Diag, avez vous des remarques complémentaires ?"}%>
      </fieldset>

      <fieldset>
      <%= f.input :photos, as: :attachinary, input_html: { "cf-questions" => "Merci d'ajouter vos photos?"}%>
      </fieldset>

      <%= link_to patients_path(@patient.id) , class: "header-item" %>

      <% end %>

app/views/shared/_form.html.erb
<%= simple_form_for @patient, html: {id: "patient-form"} do |f| %>
  <script>
    // cache immédiatement le formulaire en JS
    // pour éviter de le voir quelques dixièmes de secondes
    // le temps que conversational-form le transforme.
    // pas de "display: none", autrement CF ne marche pas comme attendu.
    document.getElementById("patient-form").style.opacity = 0;
  </script>

      <fieldset>
        <%= f.input :first_name, input_html: { "cf-questions" => "Bonjour et bienvenue sur Hair'Diag. <br>Quel est votre prénom ?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :zip_code , input_html: { "cf-questions" => "Il est possible que j'ai besoin de vous diriger vers un dermatologue Hair'Diag proche de chez vous. <br>Quel est votre code postal ?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :age, input_html: { "cf-questions" => "Quel âge avez vous ?", "cf-scrollAccerlation" => "0"}%>
      </fieldset>

      <fieldset>
        <%= f.input :loss_start_date, input_html: { "cf-questions" => "{previous-answer} ans ! Quel bel âge ! <br>A quelle année remonte votre première chute de cheveux ?"}%>
      </fieldset>

      <fieldset>
        <%= f.input :relative, collection: ["Aucun", "Père", "Mère", "Grand-père", "Grand-mère"], input_html: { "cf-questions" => " Quel membre de votre famille semble avoir le même problème ?"}%>
      </fieldset>

      <fieldset cf-questions="Avez-vous les cheveux gras ?" >
        <label for="greasy_hair-oui">Oui<input type="radio" name="patient[greasy_hair]" id="greasy_hair-oui" value="oui" tabindex="-1"
          <%= @patient.greasy_hair == "oui" ? 'checked="checked"' : "" %>>
        </label>

        <label for="greasy_hair-non">Non
          <input type="radio" name="patient[greasy_hair]" id="greasy_hair-non" value="non" tabindex="-1"
          <%= @patient.greasy_hair == "non" ? 'checked="checked"' : "" %>
          >
        </label>
      </fieldset>

      <fieldset>
        <%= f.input :refined_hair, collection: ["oui","non"], input_html: { "cf-questions" => "Avez-vous l’impression que vos cheveux se sont affinés ?"} %>
      </fieldset>

      <fieldset cf-questions="Êtes-vous sous Minoxidil ?" >
        <label for="minoxidil-oui">Oui<input type="radio" name="patient[minoxidil]" id="minoxidil-oui" value="oui" tabindex="-1"
          <%= @patient.minoxidil == "oui" ? 'checked="checked"' : "" %>>
        </label>

        <label for="minoxidil-non">Non
          <input type="radio" name="patient[minoxidil]" id="minoxidil-non" value="non" tabindex="-1"
          <%= @patient.minoxidil == "non" ? 'checked="checked"' : "" %>
          >
        </label>
      </fieldset>

      <fieldset>
        <%= f.input :minoxidil_doses, collection: [["2%",2],["5%",5]], input_html: { "cf-questions" => "A quel dose ?", "cf-conditional-patient[minoxidil]" => "oui"}%>
      </fieldset>


      <fieldset cf-questions="Avez-vous déjà effectué des greffes capillaires ?" >
        <label for="hair_transplant-oui">Oui<input type="radio" name="patient[hair_transplant]" id="hair_transplant-oui" value="oui" tabindex="-1"
          <%= @patient.hair_transplant == "oui" ? 'checked="checked"' : "" %>>
        </label>

        <label for="hair_transplant-non">Non
          <input type="radio" name="patient[hair_transplant]" id="hair_transplant-non" value="non" tabindex="-1"
          <%= @patient.hair_transplant == "non" ? 'checked="checked"' : "" %>
          >
        </label>
      </fieldset>


      <fieldset cf-questions="Lequel de ces stades correspond le mieux à votre cas ?" >
        <input cf-label="stade 1" type="radio" cf-image="http://res.cloudinary.com/dgbt9zicg/image/upload/Stade1_yzlrg4" name="patient[stage]" tabindex="1" value="0" >
        <input cf-label="stade 2" type="radio" cf-image="http://res.cloudinary.com/dgbt9zicg/image/upload/v1504186425/Stade2_jiqcsr.png" name="patient[stage]" tabindex="1" value="1" >
        <input cf-label="stade 3" type="radio" cf-image="http://res.cloudinary.com/dgbt9zicg/image/upload/v1504186425/Stade3_sgu99f.png" name="patient[stage]" tabindex="1" value="2" >
      </fieldset>

       <fieldset>
        <%= f.input :email , input_html: { "cf-questions" => "A la fin de ce questionnaire je vous enverrai votre diagnostic par email.<br>Quelle est votre adresse email ?"}%>
      </fieldset>

      <fieldset>
      <%= f.input :photos, as: :file, input_html: { "multiple" => true, "cf-questions" => "Merci d'ajouter 3 photos de votre cuir chevelu, prises de face, sur le dessus du crâne et sur un côté. <br> <img src=\"http://res.cloudinary.com/benji89/image/upload/v1504615511/Capture_d_%C3%A9cran_2017-08-07_%C3%A0_16.21.01_sariqh.jpg\"> </img>" }%>
      </fieldset>

      <fieldset>
        <%= f.input :remark, input_html: { "cf-questions" => "Merci, j'ai toutes les informations nécessaires au diagnostic Hair'Diag, avez vous des remarques complémentaires ?"}%>
      </fieldset>

      <%= f.submit %>
    <% end %>

<div id="form-loading">
  <i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
  <span class="sr-only">Loading...</span>
</div>

app/views/shared/_navbar.html.erb
<div class="header-sticky" >

  <%= link_to root_path, id: "logo" do %>
  <%= image_tag "logo_white.png" %>
  <% end %>
  <div class="header-navigation-right">
    <div class="header-links-content">
      <%= link_to "Nos dermatologues", "#", class: "header-item-content hoover" %>
      <%= link_to "FAQ", "#", class: "header-item-content hoover" %>
    </div>
    <%= link_to new_patient_path, class:"cta-start" do %>
    <div>  <button class="btn btn-cta">
      Commencer le diagnostic
    </button></div>
    <% end %>
  </div>
</div>

<div class="header-top">
  <%= link_to root_path, id: "logo" do %>
  <%= image_tag "logo_white.png" %>
  <% end %>
  <div class="header-navigation-right">
    <div class="header-links-content">
      <%= link_to "Nos dermatologues", "#", class: "header-item-content hoover" %>
      <%= link_to "FAQ", "#", class: "header-item-content hoover" %>
    </div>
    <%= link_to "Espace pro", doctor_dashboard_path, class: "header-item-right hoover" %>
  </div>
</div>


<script>
  $( ".header-sticky" ).hide();
  window.addEventListener("scroll", function() {
    if (window.scrollY > 575) {
      $('.header-sticky').fadeIn(50);

    }
    else {
      $('.header-sticky').fadeOut(50);

    }
  },false);

</script>

<!--
<script>
  $(window).on("scroll", function(e) {
  if ($(window).scrollTop() >= $(".header-sticky").height()) $(".header-sticky").fadeIn(500);
  else $(".header").fadeOut(500);
});

</script> -->


<!-- https://jsfiddle.net/SpYk3/D3DDp/-->
<!-- <script type="text/javascript">



</script> -->

app/views/shared/_sidebar-dashboard.html.erb
<div class="col-md-2">
    <div class="row side-nav" style="background: #62E1A6; background-image: linear-gradient(-180deg, rgba(42,245,152,0.00) 0%, rgba(0,0,0,0.50) 100%);">
      <div>
          <%= link_to root_path, id: "logo" do %>
          <%= image_tag "logo_white.png" %>
          <% end %>
        </div>
      <div class="menu">
        <div>
          <%= link_to doctor_dashboard_path, class: "text-icon" do %>
          <%= image_tag "icon-traiter.png" %>
          <p>Traiter une demande</p>
          <% end %>
        </div>
        <div>
          <%= link_to doctor_history_path, class: "text-icon" do %>
          <%= image_tag "icon-historic.png" %>
          <p>Historique des patients</p>
          <% end %>
        </div>
      </div>
      <div class="profile">
        <div class="profile-link">
          <%= link_to "#", class: "text-icon" do %>
          <%= image_tag "icon-profile.png" %>
          <p>Mon profil</p>
          <% end %>
        </div>
      </div>
    </div>
    </div>