config/routes.rb
Rails.application.routes.draw do

  devise_for :doctors
  root to: 'pages#home'

  # Dashboard des doctors / accueil controle
  get 'doctors/dashboard', to: 'doctors#dashboard', as: :doctor_dashboard
  # historique des cas patients assignés au doc
  get 'doctors/history', to: 'doctors#history', as: :doctor_history

  # Le doc SELECT un case (verrouille l'attribution d'un docteur au patient et sort ce patient des autres médecins)
  post 'doctors/assign-patient', to: 'doctors#assign_patient', as: :doctor_assign_patient
  #As a doctor, I can see a patient case
  get 'doctors/patient/:id', to: 'doctors#show_patient', as: :doctor_show_patient
  #As a doctor, I can SUBMIT my answer to the patient
  post 'doctors/patient/:id', to: 'doctors#create_answer', as: :doctor_create_answer

  # page de confirmation/recap et paiement coté patient / EDIT
  get 'patients/:id/validation', to: 'patients#validation', as: :validation_patient

  #As a patient, I can pay; redirect to payment confirmation controller patients; ajouter : à ID
  get 'patients/:id/payment', to: 'patients#payment', as: :payment_patient

  #message de confirmation et remerciement suite au paiement
  get 'patients/:id/thank-you', to: 'patients#thank_you', as: :thank_you_patient

  # la show du patient est celle quand il va cliquer sur le lien du cas traité par le DR
  resources :patients, only: [:new, :create, :show, :edit, :update] do
    resources :payments, only: [:new, :create]
  end
  # ajout paiements et orders

  # edition du profil docteur
  get 'profile/edit'
  get 'profile/update'

  # page de formulaire de contact avec le site
  get '/contact', to: 'pages#contact'
  # page d'info generale
  get '/about', to: 'pages#about'


  mount Attachinary::Engine => "/attachinary"
  # devise_for :users, :controllers => { registrations:  "users/registrations" }
end

app/models/patient.rb
class Patient < ApplicationRecord
  # enum pour les listes de choix dans le formulaire
  has_many :messages, dependent: :destroy
  has_many :case_assignments
  belongs_to :doctor, optional: true

  has_attachments :photos, maximum: 4
  has_attachments :documents, maximum: 3

  monetize :price_cents

  validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :gender, presence: true
  validates :zip_code, presence: true
  # validates :city, presence: true
  # validates :country, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 15, less_than_or_equal_to: 40 }
  validates :loss_start_date, presence: true
  validates :relative, presence: true
  # validates :weekly_shampoo, presence: true
  # validates :dandruff, presence: true
  validates :greasy_hair, presence: true
  validates :refined_hair, presence: true
  # validates :brushing_hair, presence: true
  # validates :shaving_hair, presence: true
  # validates :scalp_density, presence: true
  # validates :hair_thickness, presence: true
  # validates :hair_color, presence: true
  # validates :hair_type, presence: true
  # validates :vitamines, presence: true
  # validates :finasteride, presence: true
  validates :stage, presence: true
  # validates :traction_test, presence: true
  # validates :restore_area, presence: true
  # validates :technical_preference, presence: true
  validates :email, format: { with: /\A.*@.*\.[a-z]{2,}\z/ }, presence: true
  validates :minoxidil, presence: true
  validates :minoxidil_doses, presence: true, if: :minoxidil?
  validates :hair_transplant, presence: true
  # validates :hair_transplant_technic, presence: true, if: :hair_transplant?

  def minoxidil?
    minoxidil == "oui"
  end

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :set_patient, except: [:new, :create]
  skip_before_action :authenticate_doctor!

  def show
    @doctor = Doctor.where(id: @patient.doctor_id).limit(1).first
    @message = Message.where(patient_id: @patient.id).limit(1).first
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    prefill_patient
    if @patient.valid?
      @patient.save
      redirect_to validation_patient_path(@patient)
    else
      render :new
    end
  end

  def edit
    set_patient
  end

  def update
    @patient.update(patient_params)
    redirect_to validation_patient_path(@patient)
  end

  def validation
  end

  def payment
  end

  def thank_you
  end

  private

  def set_patient_status_to
    @patient.status = "payment_successful"
    @patient.save
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(
      :first_name,
      :last_name, :gender,
      :zip_code, :city,
      :country, :age, :loss_start_date,
      :relative, :weekly_shampoo, :dandruff,
      :greasy_hair, :refined_hair, :brushing_hair,
      :shaving_hair, :scalp_density,
      :hair_thickness, :hair_color,
      :hair_type, :vitamines,
      :finasteride, :stage, :traction_test,
      :restore_area, :technical_preference,
      :status, :email, :minoxidil, :minoxidil_doses,
      :hair_transplant, :hair_transplant_technic,
      :remark, photos:[])
  end

  def prefill_patient
    @patient.first_name = "Jean-Claude" if @patient.first_name.blank?
    @patient.last_name = "Dusse" if @patient.last_name.blank?
    @patient.gender = "Un homme" if @patient.gender.blank?
    @patient.email = "contact@hairdiag.com" if @patient.email.blank?
    @patient.zip_code = "13008" if @patient.zip_code.blank?
    @patient.city = "Marseille" if @patient.city.blank?
    @patient.country = "France" if @patient.country.blank?
    @patient.age = 33 if @patient.age.blank?
    @patient.loss_start_date = "2015" if @patient.loss_start_date.blank?
    @patient.relative = "Père" if @patient.relative.blank?
    @patient.weekly_shampoo = 4 if @patient.weekly_shampoo.blank?
    @patient.dandruff = "oui" if @patient.dandruff.blank?
    @patient.greasy_hair = "oui" if @patient.greasy_hair.blank?
    @patient.refined_hair = "oui" if @patient.refined_hair.blank?
    @patient.brushing_hair = "oui" if @patient.brushing_hair.blank?
    @patient.shaving_hair = "non" if @patient.shaving_hair.blank?
    @patient.scalp_density = "moyenne" if @patient.scalp_density.blank?
    @patient.hair_thickness = "moyen" if @patient.hair_thickness.blank?
    @patient.hair_color = "gris" if @patient.hair_color.blank?
    @patient.hair_type = "raide" if @patient.hair_type.blank?
    @patient.vitamines = "non" if @patient.vitamines.blank?
    @patient.minoxidil = "non" if @patient.minoxidil.blank?
    @patient.finasteride = "non" if @patient.finasteride.blank?
    @patient.hair_transplant = "non" if @patient.hair_transplant.blank?
    @patient.traction_test = "2-3 cheveux" if @patient.traction_test.blank?
    @patient.restore_area = "Front" if @patient.restore_area.blank?
    @patient.technical_preference = "F.U.E. (Unités folliculaires par extraction)" if @patient.technical_preference.blank?
    @patient.remark = "Aucune" if @patient.remark.blank?
    @patient.photos = [File.open(Rails.root.join("app","assets","images","zindine.jpg"),"r")] if @patient.photos.blank?
    # @patient.stage = File.open("http://res.cloudinary.com/dgbt9zicg/image/upload/v1504186425/Stade2_jiqcsr.png")
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/edit.html.erb
<div class="container" id="form-width">
  <div class="row">
    <div class="col-xs-6 page-part">
      <div class="side-background" style="background: #62E1A6; background-image: linear-gradient(-180deg, rgba(42,245,152,0.00) 0%, rgba(0,0,0,0.50) 100%), url('<%= image_url "background.png" %>');">
        <div>
          <%= link_to root_path, id: "logo" do %>
          <%= image_tag "logo_white.png" %>
          <% end %>
        </div>
        <div class="centerh">
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
            <!-- class active changé en actived - attention vigilence -->
              <div class="message actived">
                <div class="numbers">
                  <h3>1</h3>
                </div>
                <div class="message-body">
                  <p>Répondez aux questions de notre doc-bot Hair'Diag.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message">
                <div class="numbers">
                  <h3>2</h3>
                </div>
                <div class="message-body">
                  <p> Relisez vos réponses et confirmez </p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message">
                <div class="numbers">
                  <h3>3</h3>
                </div>
                <div class="message-body">
                  <p>Effectuez le règlement. Un dermatologue spécialiste vous fournira un avis médical sous 48h.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="center_bottom_page">
          <div class="cta-start btn btn-medium">
            <%= link_to "Retour à l'accueil", root_path, class: "header-item" %>
          </div>
        </div>

      </div>
    </div>
    <div class="col-xs-6 page-part" id="col-form">

    <%= render "shared/form" %>

    </div>
  </div>
</div>

app/views/patients/new.html.erb
<div class="container" id="form-width">
  <div class="row">
    <div class="col-xs-6 page-part">
      <div class="side-background" style="background: #62E1A6; background-image: linear-gradient(-180deg, rgba(42,245,152,0.00) 0%, rgba(0,0,0,0.50) 100%), url('<%= image_url "background.png" %>');">
        <div>
          <%= link_to root_path, id: "logo" do %>
          <%= image_tag "logo_white.png" %>
          <% end %>
        </div>
        <div class="centerh">
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message actived">
                <div class="numbers">
                  <h3>1</h3>
                </div>
                <div class="message-body">
                  <p>Répondez aux questions de notre doc-bot Hair'Diag.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message">
                <div class="numbers">
                  <h3>2</h3>
                </div>
                <div class="message-body">
                  <p> Relisez vos réponses et confirmez. </p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message">
                <div class="numbers">
                  <h3>3</h3>
                </div>
                <div class="message-body">
                  <p>Effectuez le règlement. Un dermatologue spécialiste vous fournira un avis médical sous 48h.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="center_bottom_page">
          <div class="cta-start btn btn-medium">
            <%= link_to "Retour à l'accueil", root_path, class: "header-item" %>
          </div>
        </div>

      </div>
    </div>
    <div class="col-xs-6 page-part" id="col-form">

    <%= render "shared/form" %>

    </div>
  </div>
</div>

app/views/patients/payment.html.erb
<div class="container" id="form-width">
  <div class="background" >
    <div class="row">
      <div class="col-xs-6 page-part" style="background: #62E1A6; background-image: linear-gradient(-180deg, rgba(42,245,152,0.00) 0%, rgba(0,0,0,0.50) 100%), url('<%= image_url "background.png" %>'); ">
        <div>
          <%= link_to root_path, id: "logo" do %>
          <%= image_tag "logo_white.png" %>
          <% end %>
        </div>
        <div class="centerh">
           <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message">
                <div class="numbers">
                  <h3>1</h3>
                </div>
                <div class="message-body">
                  <p>Répondez aux questions de notre doc-bot Hair'Diag pour que vos réponses soient analysées par un demartologue.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message">
                <div class="numbers">
                  <h3>2</h3>
                </div>
                <div class="message-body">
                  <p> Relisez vos réponses et confirmez. </p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message actived">
                <div class="numbers">
                  <h3>3</h3>
                </div>
                <div class="message-body">
                  <p> Payez et envoyez vos informations à un dermatologue Hair'Diag.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-xs-6 page-part payment">
        <div class="container-home centerh">
          <div class="row validation-container">
            <div class="col-md-10 col-md-offset-1">
              <h2>Cher <%= @patient.first_name %>, nous avons bien enregitré vos informations.</h2>
              <h3> Afin qu'un dermatologue certifié puisse rapidement établir un pré-diagnostic,
              nous vous invitons maintenant à procéder au paiement.</h3>
              <h3>
              <%= form_tag patient_payments_path(@patient) do %>
              <article>
                <h2><label class="amount">
                  <span>Prix : <%= humanized_money_with_symbol(@patient.price) %></span> </h2>
                </label>
              </article>

              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-name="My consult"
              data-email="<%= @patient.email %>"
              data-description="Consultation <%= @patient.first_name %>"
              data-amount="<%= @patient.price_cents %>"
              data-currency="<%= @patient.price.currency %>"
              data-label="Payer maintenant"
              data-locale="auto">
              </script>
              <% end %>
              </h3>
            </div>
          </div>
        </div>
        <div class="center_bottom_page wrapper-valitation-buttons">
          <div class="btn btn-medium .payment">
            <%= link_to "Retour à l'étape 2", validation_patient_path(@patient) , class: "header-item" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/show.html.erb
<!-- Cette show est la show lorsque le patient clique sur le lien lui permettant d'accéder à son cas-->


  <div class="container-view">
    <div class="col-md-2 ">
      <div class="row view-side-bar" style="background: #62E1A6; background-image: linear-gradient(-180deg, rgba(42,245,152,0.00) 0%, rgba(0,0,0,0.50) 100%);">
        <div>
          <%= link_to root_path, id: "logo" do %>
          <%= image_tag "logo_white.png" %>
          <% end %>
        </div>
        <div class="answer-nav">
          <div class="answer-nav-item">
            <%= link_to doctor_dashboard_path, class: "text-icon" do %>
            <%= image_tag "icon-traiter.png" %>
            <p>Ma recommandation personnalisée</p>
            <% end %>
          </div>
          <div class="answer-nav-item">
            <%= link_to doctor_history_path, class: "text-icon" do %>
            <%= image_tag "icon-historic.png" %>
            <p>Ma fiche patient</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-10">
      <div class="row answer-container">
        <div>
          <div>
            <div class="header-answer">
              <h2>Patient: <%= @patient.first_name.to_s + " " + @patient.last_name.to_s %> </h2>
              <p>Cas envoyé le <%=@patient.created_at.strftime("%d-%m-%Y à %Hh%M") %>. </p>
              <p>Cas étudié le <%= @message.created_at.strftime("%d-%m-%Y à %Hh%M") %> par le Dr. <%= @doctor.first_name + " " + @doctor.last_name.to_s %> </p>
              <p>Diagnostic: <%= @message.subject.to_s.downcase %> </p>
            </div>
          </div>
          <div class="message-answer">
            <%= image_tag "photo-expert1.png" %>
            <div class="message-answer-container">
              <div class="sender">
              <%= "#{@doctor.first_name} #{@doctor.last_name.to_s}" %>
              </div>
              <div class="content">
                <!--%= @message.content %-->
                <%= simple_format(@message.content)  %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/patients/thank_you.html.erb
<div class="container-home">

  <div class="home-background thanks" style="background: #62E1A6; background-image: linear-gradient(-180deg, rgba(42,245,152,0.00) 0%, rgba(0,0,0,0.50) 100%), url('<%= image_url "background.png" %>');">
    <%= render "shared/navbar"%>
    <div class="general-wrapper home-content-wrapper">
     <div class="home-content">
       <%= image_tag "logo-no-baseline.png" %>
       <h2>Votre paiement a bien été accepté, merci pour votre confiance. </h2>
       <h3>Un dermatologue certifié vous répondra par mail sous 48h. </h3>

       <%= link_to root_path, class:"cta-start" do %>
       <div>
        <button class="btn btn-cta">
          <%= link_to "Retour à l'accueil", root_path, class: "header-item" %>
        </button>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/patients/validation.html.erb
<div class="container" id="form-width">
  <div class="background" >
    <div class="row">
      <div class="col-xs-6 page-part" style="background: #62E1A6; background-image: linear-gradient(-180deg, rgba(42,245,152,0.00) 0%, rgba(0,0,0,0.50) 100%), url('<%= image_url "background.png" %>'); ">
        <div>
          <%= link_to root_path, id: "logo" do %>
          <%= image_tag "logo_white.png" %>
          <% end %>
        </div>
        <div class="centerh">
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message">
                <div class="numbers">
                  <h3>1</h3>
                </div>
                <div class="message-body">
                  <p>Répondez aux questions de notre doc-bot Hair'Diag Pour que vos réponses soient analysées par un demartologue.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message actived">
                <div class="numbers">
                  <h3>2</h3>
                </div>
                <div class="message-body">
                  <p> Relisez vos réponses et confirmez. </p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="message">
                <div class="numbers">
                  <h3>3</h3>
                </div>
                <div class="message-body">
                  <p> Payez et envoyez vos informations à un dermatologue Hair'Diag.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="center_bottom_page">
            <div class="cta-start btn btn-medium">
              <%= link_to "Retour à l'accueil", root_path, class: "header-item" %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-xs-6 page-part">
        <div class="row validation-container">
          <div class="col-md-10">
            <div class="row dashboard-infos patients-show">

              <h2 id="confirmation-message">Merci de prendre le temps de relire et confirmez vos informations </h2>
              <div class="patients-details">
                <div>
                  <h3>Informations pratiques <a data-toggle="collapse" data-target="#info-pratiques">
                    <i class="fa fa-minus collapse-icon"aria-hidden="true"></i></a>
                  </h3>
                  <div class="row collapse in" id="info-pratiques">
                    <div class="col-md-6 info-pratiques-input">
                      <p>Patient</p>
                      <span><%= "#{@patient.first_name.to_s} #{@patient.last_name.to_s}"%></span>
                    </div>
                    <div class="col-md-6 info-pratiques-input">
                      <p>Email</p>
                      <%= "#{@patient.email.to_s}"  %>
                    </div>
                    <div class="col-md-6 info-pratiques-input">
                      <p>Genre</p>
                      <%= "#{@patient.gender.to_s == "Un homme" ?
                      "Homme".downcase : "Femme".downcase}" %>
                    </div>
                    <div class="col-md-6 info-pratiques-input">
                      <p>Age</p>
                      <%= "#{@patient.age} ans" %>
                    </div>
                    <div class="col-md-6 info-pratiques-input">
                      <p>Localité</p>
                      <%= "#{@patient.city.to_s}, #{@patient.zip_code.to_s} (#{@patient.country.to_s}) "  %>
                    </div>
                  </div>
                </div>
                <div>
                  <h3> Contexte médical <a data-toggle="collapse" data-target="#context-medical">
                    <i class="fa fa-minus collapse-icon"aria-hidden="true"></i></a>
                  </h3>
                  <div class="row collapse in" id="context-medical">
                    <div class="col-md-12 context-medical-input-tf">
                      Couleur de cheveux <p> <%= @patient.hair_color.to_s %></p>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Type de cheveux <p><%= @patient.hair_type.to_s %></p>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Epaisseur des cheveux <p><%= @patient.hair_thickness.to_s %></p>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      A l'impression que ses cheveux se sont affinés :
                      <% if @patient.refined_hair.to_s =="Oui" %>
                      <p>oui <i class="fa fa-check-square-o" aria-hidden="true"></i></p>
                      <% else %>
                      <p>non <i class="fa fa-times false-red" aria-hidden="true"></i></p>
                      <% end %>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Membre de sa famille ayant le même problème
                      <% if @patient.relative.to_s == "Père" || @patient.relative.to_s == "Grand-père" %>
                      <p> <%= "son #{@patient.relative.to_s.downcase}" %></p>
                      <% elsif @patient.relative.to_s == "Mère" || @patient.relative.to_s == "Grand-mère" %>
                      <p> <%= "sa #{@patient.relative.to_s.downcase}" %></p>
                      <% else %>
                      <p>Aucun</p>
                      <% end %>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Nombre de shampoings par semaine <p> <%= "#{pluralize(@patient.weekly_shampoo, "shampoing")}"%></p>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Pellicules
                      <% if @patient.dandruff.to_s == "Oui" %>
                      <p>oui <i class="fa fa-check-square-o" aria-hidden="true"></i></p>
                      <% else %>
                      <p>non <i class="fa fa-times false-red" aria-hidden="true"></i></p>
                      <% end %>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Cheveux gras
                      <% if @patient.greasy_hair.to_s == "Oui" %>
                      <p>oui <i class="fa fa-check-square-o" aria-hidden="true"></i></p>
                      <% else %>
                      <p>non <i class="fa fa-times false-red" aria-hidden="true"></i></p>
                      <% end %>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Fait des tresses / défrisages / brushings
                      <% if @patient.brushing_hair.to_s == "Oui" %>
                      <p>oui <i class="fa fa-check-square-o" aria-hidden="true"></i></p>
                      <% else %>
                      <p>non <i class="fa fa-times false-red" aria-hidden="true"></i></p>
                      <% end %>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Se rase régulièrement tout ou une partie du cuir chevelu
                      <% if @patient.shaving_hair.to_s == "Oui" %>
                      <p>oui <i class="fa fa-check-square-o" aria-hidden="true"></i></p>
                      <% else %>
                      <p>non <i class="fa fa-times false-red" aria-hidden="true"></i></p>
                      <% end %>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Estime la densité à l'arrière de son cuir chevelu
                      <p> <%= "#{@patient.scalp_density.to_s.downcase}" %></p>
                    </div>
                  </div>
                </div>
                <div>
                  <h3> Situation capillaire <a data-toggle="collapse" data-target="#situation-capillaire">
                    <i class="fa fa-minus collapse-icon"aria-hidden="true"></i></a>
                  </h3>
                  <div class="row collapse in" id="situation-capillaire">
                    <div class="col-md-12 context-medical-input-tf">
                      Prend des vitamines
                      <% if @patient.vitamines.to_s == "Oui" %>
                      <p>oui <i class="fa fa-check-square-o" aria-hidden="true"></i></p>
                      <% else %>
                      <p>non <i class="fa fa-times false-red" aria-hidden="true"></i></p>
                      <% end %>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Prend du finasteride
                      <% if @patient.finasteride.to_s == "Oui" %>
                      <p>oui <i class="fa fa-check-square-o" aria-hidden="true"></i></p>
                      <% else %>
                      <p>non <i class="fa fa-times false-red" aria-hidden="true"></i></p>
                      <% end %>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Stade de la perte de cheveux <p><%= @patient.stage.to_s %></p>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Résultat du test de traction <p><%= @patient.traction_test.to_s %></p>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Zone de restauration souhaitée <p><%= @patient.restore_area.to_s %></p>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Technique de restauration préférée <p>F.U.E</p>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      Prend du Minoxidil
                      <% if @patient.minoxidil == "Oui"  %>
                      <p>oui (<%="#{@patient.minoxidil_doses} doses"%>)</p>
                      <% else %>
                      <p>non <i class="fa fa-times false-red" aria-hidden="true"></i></p>
                      <% end %>
                    </div>
                    <div class="col-md-12 context-medical-input-tf">
                      A déjà effectué une greffe capillaire
                      <% if @patient.hair_transplant.to_s == "Oui" %>
                      <p>oui <i class="fa fa-check-square-o" aria-hidden="true"></i></p>
                      <% else %>
                      <p>non <i class="fa fa-times false-red" aria-hidden="true"></i></p>
                      <% end %>
                    </div>
                    <% if @patient.hair_transplant == "oui" %>
                    <div class="col-md-12 context-medical-input-tf">
                      Technique de transplantation souhaitée <p><%= @patient.hair_transplant_technic.to_s %></p>
                    </div>
                    <% end %>
                  </div>
                </div>
                <div class="patient-photos">
                  <h3> Photos <a data-toggle="collapse" data-target="#patient-pictures">
                    <i class="fa fa-minus collapse-icon"aria-hidden="true"></i></a>
                  </h3>
                  <div class="row collapse in" id="patient-pictures">
                    <% if @patient.photos? %>
                    <% @patient.photos.each do |photo| %>
                    <div class="col-md-4 grow">
                      <%= cl_image_tag photo.path, height: 200, width: 200, crop: :fill %>
                    </div>
                    <% end %>
                    <% else %>
                    <p>Vous n'avez pas chargé de photo</p>
                    <% end %>
                  </div>
                </div>
                <div>
                  <div class="wrapper-valitation-buttons">
                    <%= link_to edit_patient_path(@patient), class: "" do %>
                    <button class="btn btn-medium">
                      <p>Corriger le formulaire</p>
                    </button>
                    <% end %>

                    <%= link_to payment_patient_path(@patient), class: "" do %>
                    <button class="btn btn-cta">
                      <p>Valider et payer</p>
                    </button>
                    <% end %>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>