config/routes.rb
Rails.application.routes.draw do

  devise_for :doctors
  root to: 'pages#home'

  # Dashboard des doctors / accueil controle
  get 'doctors/dashboard', to: 'doctors#dashboard', as: :doctor_dashboard
  # historique des cas patients assignés au doc
  get 'doctors/history', to: 'doctors#history', as: :doctor_history

  # Le doc SELECT un case (verrouille l'attribution d'un docteur au patient et sort ce patient des autres médecins)
  post 'doctors/assign-patient', to: 'doctors#assign_patient', as: :doctor_assign_patient
  #As a doctor, I can see a patient case
  get 'doctors/patient/:id', to: 'doctors#show_patient', as: :doctor_show_patient
  #As a doctor, I can SUBMIT my answer to the patient
  post 'doctors/patient/:id', to: 'doctors#create_answer', as: :doctor_create_answer

  # page de confirmation/recap et paiement coté patient / EDIT
  get 'patients/:id/validation', to: 'patients#validation', as: :validation_patient

  #As a patient, I can pay; redirect to payment confirmation controller patients; ajouter : à ID
  get 'patients/:id/payment', to: 'patients#payment', as: :payment_patient

  #message de confirmation et remerciement suite au paiement
  get 'patients/:id/thank-you', to: 'patients#thank_you', as: :thank_you_patient

  # la show du patient est celle quand il va cliquer sur le lien du cas traité par le DR
  resources :patients, only: [:new, :create, :show, :edit, :update] do
    resources :payments, only: [:new, :create]
  end
  # ajout paiements et orders

  # edition du profil docteur
  get 'profile/edit'
  get 'profile/update'

  # page de formulaire de contact avec le site
  get '/contact', to: 'pages#contact'
  # page d'info generale
  get '/about', to: 'pages#about'


  mount Attachinary::Engine => "/attachinary"
  # devise_for :users, :controllers => { registrations:  "users/registrations" }
end

app/models/doctor.rb
class Doctor < ApplicationRecord

  has_many :case_assignments
  has_many :patients
  validates :first_name, length: { minimum: 2 }, presence: true
  validates :last_name, length: { minimum: 2 }, presence: true
  validates :adress, presence: true
  validates :zip_code, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :description, length: { minimum: 20 }, presence: true
  validates :phone_number, uniqueness: true, presence: true
  validates :specialty, presence: true
  validates :RPPS, uniqueness: true, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  after_create :send_welcome_email

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def send_welcome_email
    DoctorMailer.welcome(self).deliver_now
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController


 def dashboard
  @waiting_patient = Patient.where(status: "assigned", doctor_id: current_doctor.id).limit(1).first
  if @waiting_patient.nil?
    @patients_available = Patient.where(status: "payment_successful")
  else
    redirect_to doctor_show_patient_path(@waiting_patient)
  end
end

 def history
  @patients = Patient.where(doctor_id: current_doctor.id)
 end


 def assign_patient
  @patient_selected = Patient.where(status: "payment_successful").to_a.last

  if @patient_selected.nil?
    flash[:alerte] = "Il n'y a pas de cas en attente d'être traité"
    redirect_to doctor_dashboard_path
  else
    @patient_selected.doctor_id = current_doctor.id
    @patient_selected.status = "assigned"
    @patient_selected.save!
    redirect_to doctor_show_patient_path(@patient_selected)
  end

 end

 def show_patient
  @doctor = current_doctor
  @patient = Patient.find(params[:id])
  @recommendation = Message.new
 end

 def create_answer
  @patient = Patient.find(params[:id])
  @recommendation = Message.new(message_params)
  @recommendation.patient_id = @patient.id
  if @recommendation.save!
    @patient.status = "answered"
    @patient.save!
    redirect_to doctor_dashboard_path
    flash[:notice] = "Felicitations, vous venez de traiter un patient !"
  else
    render "doctors/show_patient"
    flash[:alert] = "Aie, il semblerait que vous ayez fait une erreurs dans la redaction de votre recommendation!"
  end
end

private

 def message_params
   params.require(:message).permit(:subject, :content)
 end

end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/dashboard.html.erb
 <div class="dashboard-container">
  <div class="row">
    <%= render "shared/sidebar-dashboard"%>
    <div class="col-md-10">
      <div class="row dashboard-infos">
        <div class="dashboard-main-content">
          <div class="#">
            <h2>Bonjour <%= current_doctor.first_name  %>,</h2>
            <p>Bienvenue sur votre tableau de bord Hair'Diag.</p>
            <ol>
              <li>Cliquez sur "voir un patient"</li>
              <li>Prenez le temps d'étudier le cas</li>
              <li>Apportez-y une reponse adaptée</li>
            </ol>
          </div>
          <div class="see-patient">
            <% if @patients_available.count == 0 %>
            <p>Il n'y a actuellement aucun patient en attente d'être soigné, vous serez alerté quand une demande de traitement vous sera parvenue.</p>
            <% else %>
            <%= link_to doctor_assign_patient_path, class:"cta-start", method: :post do %>
            <div>
              <button class="btn btn-cta">
                <p>Voir un patient</p>
                <%= image_tag "icon-microscope.png", class: "icon-microscope" %>
              </button>
            </div>
            <% end %>
            <p>Il y a actuellement <strong><%= @patients_available.count %></strong> <%= t('patients', count: @patients_available.count) %>.</p>
            <% end %>
          </div>
        </div>
        <div class="dashboard-boiler-plate">
          <h2>Note:</h2>
          <p>En arrivant sur cette page, vous engagez votre responsabilité et celle de votre profession. En cliquant sur le bouton "voir un patient" ci-dessous, vous vous engagez à étudier son cas conformément au contrat que vous avez signé avec nous et à y répondre en moins de 48h.</p>
        </div>


    </div>
    </div>
  </div>
</div>

app/views/doctors/history.html.erb
<div class="dashboard-container">
  <div class="row">
    <%= render "shared/sidebar-dashboard"%>
    <div class="col-md-10">
      <div class="row dashboard-infos">
        <div class="dashboard-main-content">
          <div class="#">
            <h1>Here is all your cases</h1>

            <!-- Ici je met toutes les donnees du patient, par cas, a reduire en fonction de ce que l'on veut dans le cas et le numero correspond au statut du patient-->
            <% @patients.each do |patient| %>
            <% if @patients.nil? %>
            <p>Vous n'avez pas encore traité de patient!</p>
            <% else %>
            <% if patient.doctor_id == current_doctor.id %>
            <div class="case">
              <%= image_tag patient.photos.first.path , class: "avatar-large" %>
              <div class="case-name">
                <%=  %>
                <%= link_to patient.first_name + patient.last_name.to_s, doctor_show_patient_path(patient), class: "h4" %>
              </div>
              <div class="case-body">
                <p><strong> <%= patient.city %></strong></p>
                <p>
                  Pris en charge le <%= patient.created_at  %>
                  <%= patient.stage %>
                </p>
              </div>
              <div class="case-status">
                <p class="status pending"><%= patient.status %></p>
              </div>
            </div>
            <% end %>
            <% end %>
            <% end %>
            <%= link_to "Retourner au Dashboard" , doctor_dashboard_path, class: "h4" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doctors/refresh_count.js.erb
// $(".see-patient").html("<%= escape_javascript(render 'partial', data: @patients_available) %>");